### ISSUE TITLE
Missing variables/justification for FPS section

### ISSUE THREAD

**Issue by JMiller-Disco** [AdobeDocs/media-analytics.en#11]
Issue in ./help/metrics-and-metadata/quality-parameters.md

The FPS section, [here](https://docs.adobe.com/content/help/en/media-analytics/using/metrics-and-metadata/quality-parameters.html#FPS), is missing any information as to how this value is used or reported. There is not Analytics variable mentioned, implying that it isn't accessible from the Heartbeat Launch extension and/or it cannot be accessed through processing rules. And, there's no reporting variable to actually use "Frames Per Second".

What's the point in setting this variable or pre-defining it if it isn't even a reported value?

**Comment by czakdesign** [comment]
Thank you for reporting this issue with the documentation. We are currently updating the content to address this issue.
