### ISSUE TITLE
Parameter Types

### ISSUE THREAD

**Issue by davidfrogley** [AdobeDocs/media-analytics.en#13]
Issue in ./help/media-collection-api/mc-api-ref/mc-api-req-params.md

It would be really helpful to list the TYPES of the parameters along with the names, descriptions, whether or not they're required, and which call they're used on.

**Comment by czakdesign** [comment]
Thank you for the suggestion. I have passed along your request to our engineers and will work to add the list of 'types' of parameters along with the names, descriptions, and whether or not they're required - and which call they're used on.
