### ISSUE TITLE
Action Ad start samples are not consistent with API Reference - field media.ad.podFriendlyName

### ISSUE THREAD

**Issue by Khalanirek** [AdobeDocs/media-analytics.en#14]
Issue in ./help/media-collection-api/mc-api-timelines/mc-api-timeline-1.md

Action Ad start samples are not consistent with API Reference - field media.ad.podFriendlyName is missing in API Reference, but in samples it is available.

**Comment by czakdesign** [comment]
Regarding the issue in ./help/media-collection-api/mc-api-timelines/mc-api-timeline-1.md

The field "media.ad.podFriendlyName" is listed in the API Reference in the Ad Data section:

https://experienceleague.adobe.com/docs/media-analytics/using/media-collection-api/mc-api-ref/mc-api-req-params.html?lang=en#ad-data

Please feel free to reach out if you have any other questions or comments.
Thanks
