### ISSUE TITLE
Incorrectly labelled eventType

### ISSUE THREAD

**Issue by JMiller-Disco** [AdobeDocs/media-analytics.en#2]
When a chapter ends, it should have the eventType of "chapterComplete" as versus what is currently listed as "chapterEnd".

chapterEnd is not part of the list of existing event types, [here](https://docs.adobe.com/content/help/en/media-analytics/using/media-collection-api/mc-api-ref/mc-api-event-types.html#chaptercomplete), nor is it a request that is actually send from a live implementation.

**Comment by czakdesign** [comment]
Thank you for submitting this issue.  chapterEnd is no longer documented.  

[chapterComplete](https://experienceleague.adobe.com/docs/media-analytics/using/media-collection-api/mc-api-ref/mc-api-event-types.html?lang=en#chaptercomplete) is the correct eventType.
