### ISSUE TITLE
Add Clarity Between Action 10 & 11

### ISSUE THREAD

**Issue by JMiller-Disco** [AdobeDocs/media-analytics.en#5]
The _implementation detail_ of **Action 10** states that the "playing" state had persisted throughout the ad break.
However, the _implementation detail_ for **Action 11** mentions that the player needs to be put back into a "playing" state after sending adBreakComplete event. Does this mean that the event unsets the "playing" state? If so, does it get set to some other state temporarily? It would be useful to answer this in the documentation--perhaps as a third sentence to the _implementation details_ of **Action 10**.

**Comment by czakdesign** [comment]
Thank you for submitting these questions. We are currently updating the documentation to clarify the implementation detail.
