### ISSUE TITLE
Needs Clarification: Media concurrent viewers

### ISSUE THREAD

**Issue by JMiller-Disco** [AdobeDocs/media-analytics.en#7]
The initial [**Media concurrent viewers**](https://docs.adobe.com/content/help/en/media-analytics/using/media-reports/media-default-reports/media-concurrent-viewers.html) page doesn't mention that this report is still listed in _BETA_ and that it isn't even available through Workspace yet.

It would be more helpful to explicitly mention this so that Analysts reading the documentation don't start relying on this metric for business-critical decisions. Additionally, there could be more clarification made within the v1.4 API page, [here](https://docs.adobe.com/content/help/en/media-analytics/using/media-reports/media-default-reports/get-concurrent-json.html), to specify that this _Beta_ metric is only exportable by users with product admin level permissions. Also, the linked v1.4 API documentation, Github and Swagger, don't mention the use of this metric at all, and aren't really appropriate in this context unless presented as a general introduction guide to the v1.4 API.

Finally, given that v1.4 API is meant to become deprecated this year, what are the plans for this metric?

**Comment by czakdesign** [comment]
Thank you for your feedback.  The [Media Concurrent Viewers](https://experienceleague.adobe.com/docs/media-analytics/using/media-reports/media-default-reports/media-concurrent-viewers.html?lang=en) feature is no longer in Beta.

For additional reference, please see the following documentation:

- [Media concurrent viewers report](https://experienceleague.adobe.com/docs/media-analytics/using/media-reports/media-default-reports/media-concurrent-viewers.html?lang=en)
- [Media concurrent viewers panel](https://experienceleague.adobe.com/docs/analytics/analyze/analysis-workspace/panels/media-concurrent-viewers.html?lang=en)

For additional information on the API, please see [Get Concurrent Viewers JSON report data with Analytics 2.0 APIs](https://docs.adobe.com/content/help/en/media-analytics/using/media-reports/media-default-reports/get-concurrent-json20.html).
