### ISSUE TITLE
Switch to more inclusive language 

### ISSUE THREAD

**Issue by macdonst** [AdobeDocs/media-analytics.en#8]
Could you please take some time in the next few days to make changes to some terminology in your repos and content as much as is possible:

- Whitelist/blacklist to Allowed List and Blocked List (or Approve List/Deny List - some software uses this instead) respectively. Google and many developers are formalizing allowlist and blocklist. You might want to lobby for those terms to be used in the UI.
- Master/Slave to master and replica (or subordinate, if that makes more sense) respectively.

If you cannot remove the term because the writing for example reflects the UI or the code, please make a note and send me an email to Grp-opensourceoffice@adobe.com so we can bring it that team’s attention. Thanks for your efforts in this matter.

**Comment by czakdesign** [comment]
Hi,  We have updated our documentation to replace references to whitelist/blacklist as well as any references to master/slave. Thank you for the suggestion. And I understand, it's about time attention was brought to this matter.
